### ISSUE TITLE
처리된 파일은 어디에 저장되나요?

### ISSUE THREAD

**Issue by AppleCEO** [softdevstory/pdfForSlideshare#1]
프린트 처리 중인 페이지 쭉 올라간 뒤에 창이 그냥 닫히는데

저장 위치를 지정하라는게 따로 안떠서요.

어디에 저장되나요? 제대로 동작 안한걸까요?

**Comment by softdevstory** [comment]
꽤 오래동안 저도 안써봐서 기억이 가물하네요.
따로 지정하는 과정은 구현안되어 있고, 바탕화면에 떨궜던 걸로 기억해요.

**Comment by AppleCEO** [comment]
맥북이라 따로 저장은 안되는거 같네욥.. 답변 고맙습니다.
LANG=C LC_ALL=C sed -i '' s'|/Registry (Adobe) /Ordering (Korea1) /Supplement [0-9]|/Registry(Adobe) /Ordering(Identity) /Supplement 0|g' observerPattern.pdf

명령어로 해결했네요
